apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: host-path
    image: nginx
    command: ["sleep", "3600"]
    volumeMounts:
    - name: host-volume
      mountPath: /mnt/host
  volumes:
  - name: host-volume
    hostPath:
      path: /tmp
