apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-viewer
  namespace: landlords
rules:
# Только просмотр секретов (без изменения)
- apiGroups: [""]
  resources:
    - "secrets"
  verbs: ["get", "list", "watch"]