apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: emptydir
    image: nginx
    command: ["sleep", "3600"]
    volumeMounts:
    - name: tmp-volume
      mountPath: /mnt/tmp
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
  volumes:
  - name: tmp-volume
    emptyDir: {}
